# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
import sys
# from KeyAssigningWidget import Ui_Form
import pandas as pd
from random import shuffle
import numpy as np
import os


class ClickableLabel(QtWidgets.QLabel):
    clicked = QtCore.pyqtSignal()
    CtrlClicked = QtCore.pyqtSignal()
    Rclicked = QtCore.pyqtSignal()
    CtrlRclicked = QtCore.pyqtSignal()
    
    def setList(self,List):
        self.Imagelist = List
        self.currentIndex = 0
        self.redhotmap = QtGui.QPixmap(self.Imagelist[0])
        self.redhotmap = self.redhotmap.scaled(self.geometry().width(),self.geometry().height(),1,1)
        self.setPixmap(self.redhotmap)
    
    def bringNextContenderOut(self):
        self.currentIndex += 1
        self.redhotmap = QtGui.QPixmap(self.Imagelist[self.currentIndex])
        self.redhotmap = self.redhotmap.scaled(self.geometry().width(),self.geometry().height(),1,1)
        self.setPixmap(self.redhotmap)
        
        
    def getCurrentcontenderName(self):
        return Path(self.Imagelist[self.currentIndex]).stem
        
        
    def mouseReleaseEvent(self, QMouseEvent):
        print(QMouseEvent)
        modifiers = QtWidgets.QApplication.keyboardModifiers()
        # import pdb; pdb.set_trace()
        leftPressed = QMouseEvent.button() == QtCore.Qt.LeftButton
        rightPressed = QMouseEvent.button() == QtCore.Qt.RightButton
        ctrlPressed = modifiers == QtCore.Qt.ControlModifier
        if leftPressed and not ctrlPressed:
            self.clicked.emit()
        if rightPressed and not ctrlPressed :
            self.Rclicked.emit()
        if leftPressed and ctrlPressed:
            self.CtrlClicked.emit()
        if rightPressed and ctrlPressed:
            self.CtrlRclicked.emit()

class Ui_MainWindow(object):
    path = sys.argv[1]
    
    def setupList(self):
        self.listI = [str(x) for x in Path(self.path).glob('*.jpg')]
        listOfName =  [Path(x).stem for x in self.listI]
        shuffle(self.listI)
        self.dffilename = Path(self.path) / 'MatchRecord.csv'
        
        weightM = np.zeros((len(listOfName),len(listOfName)))
        df = pd.DataFrame(weightM,columns=listOfName,index=listOfName)
        # assert len(listOfName) != len(self.listI)
        if self.dffilename.is_file():
            df1 = pd.read_csv(str(self.dffilename))
            df1 = df1.set_index(df1.columns[0])
            # import pdb;pdb.set_trace()
            df = df1 + df
            df = df[listOfName].filter(items=listOfName,axis=0)
            df = df.fillna(0.)
        self.df = df
        
    def showTheWinner(self,MainWindow):
        print('current champion score is:' , self.df.sum(1).max())
        p = Path(self.path) / (self.df.sum(1).idxmax() + '.jpg')
        template = 'start "C:\Program Files\IrfanView\i_view64.exe\" "%s"' %  str(p)
        os.system(template)
        print(p)
        
    def showTheLoser(self,MainWindow):
        print('current champion score is:' , self.df.sum(1).min())
        p = Path(self.path) / (self.df.sum(1).idxmin() + '.jpg')
        template = 'start "C:\Program Files\IrfanView\i_view64.exe\" "%s"' %  str(p)
        os.system(template)
        print(p)
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.closeEvent = lambda e: self.df.to_csv(self.dffilename)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.h = MainWindow.geometry().height()
        h = self.h
        self.w = MainWindow.geometry().width()
        w = self.w
        self.setupList()
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, w, h))
 
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.label = ClickableLabel(self.horizontalLayoutWidget)
        # self.label.setGeometry(QtCore.QRect(0, 0, w, h))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.resize(w/2,h)
        self.label.setList(self.listI[0::2])
        # print(self.listI[223])
        # redhotmap = QtGui.QPixmap(self.listI[223])
        # redhotmap = QtGui.QPixmap("D:/paradise/stuff/Images/walls/juggernaut1_huc656199de66b421ef22ad489780ef428_234989_1920x1080_resize_q75_box.jpg")
        # redhotmap = redhotmap.scaled(200,200,0)
        # self.label.setPixmap(redhotmap)
        self.label.setScaledContents(False)
        self.horizontalLayout.addWidget(self.label)
        self.LeftImage = ClickableLabel(self.horizontalLayoutWidget)
        self.LeftImage.resize(w/2,h)
        self.LeftImage.setList(self.listI[1::2])
        self.LeftImage.setObjectName("LeftImage")
        # self.LeftImage.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.horizontalLayout.addWidget(self.LeftImage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Left), MainWindow, activated=lambda :self.arraowEvent(1))
        QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Right), MainWindow, activated=lambda :self.arraowEvent(0))
        QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Up), MainWindow, activated=lambda :self.showTheWinner(MainWindow))
        QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Down), MainWindow, activated=lambda :self.showTheLoser(MainWindow))

        # QtWidgets.QShortcut(QtGui.QKeySequence(QtCore.Qt.Key_Right), MainWindow, activated=self.label.bringNextContenderOut)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def arraowEvent(self,WinningSide):
        Winner = self.label
        Loser = self.LeftImage
        if WinningSide == 0:
            Winner = self.LeftImage
            Loser = self.label
        winnerName = Winner.getCurrentcontenderName()
        loserName = Loser.getCurrentcontenderName()
        Loser.resize(MainWindow.geometry().width()/2,MainWindow.geometry().height()-30)
        
        Loser.bringNextContenderOut()
        # self.close()
        self.df[loserName][winnerName] = 1
        self.df[winnerName][loserName] = -1
        # print(self.df[winnerName][loserName])
        
        # self.df.to_csv(self.dffilename)
    
    # def getCurrentChampion(self):
        # pass

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ClickOnTheWinner"))
        # self.label.setText(_translate("MainWindow", "TextLabel"))
        # self.LeftImage.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    # print('Hello')
    # ui.df.to_csv(ui.dffilename)
    sys.exit(app.exec_())
